### ISSUE TITLE
Ability to copy the API response and also the programmatic code

### ISSUE THREAD

**Issue by iSumitBanik** [rohinivsenthil/postcode#14]
First of all, Thanks for creating this wonderful extension.

Can we please have a button indicating a copy to the clipboard for the following use cases? As I am into API testing by implementing this would make my task easier a lot.

Thanks,
Sumit

**Comment by rohinivsenthil** [comment]
@iSumitBanik Hi, thanks for the suggestion! A copy to clipboard button is now added with the latest release (v1.3.1) thanks to @Mukundan314 🎉

![postcode-copy](https://user-images.githubusercontent.com/42040329/120953324-5c10d580-c76a-11eb-85a2-4818e80fb858.gif)
