### ISSUE TITLE
Authorization not working

### ISSUE THREAD

**Issue by FStefanni** [rohinivsenthil/postcode#23]
Hi,

I tested the extension with a GET API requiring basic auth.
I set the credentials in the "Authorization" tab, and selected the "Basic Auth" option.
Unfortunately it did not work.

It worked instead if I put directly the Authorization header in the header section.

I have not checked if the same problem happens with the bearer token authentication (but it could be quite likely).

Regards.

**Comment by rohinivsenthil** [comment]
Hi @FStefanni! Thanks for pointing out this bug. It is now fixed thanks to @Mukundan314's PR

**Comment by FStefanni** [comment]
Hi,

I confirm it now works perfectly. Thank you.

Regards.
