### ISSUE TITLE
add the ability to ignore certificate issues for localhost

### ISSUE THREAD

**Issue by maciejjankowski** [rohinivsenthil/postcode#26]
currently when issuing a request to localhost I get 
`Could not send request
Error: unable to verify the first certificate`

despite running `dotnet dev-certs https --trust` first

**Comment by zhaobzh** [comment]
the same problem to me.

**Comment by mrsauravsahu** [comment]
Yeah, I ran into the same issue with a .NET Core API which uses https. I have a fix, after going through the axios' github. Can create a PR. 
@rohinivsenthil can we add like an options tab with a strictSSL switch? We can set it to 'off' to conditionally add this change.

**Comment by rohinivsenthil** [comment]
@mrsauravsahu thanks for helping out. And yes! – that'll be super helpful 😄

**Comment by rohinivsenthil** [comment]
@maciejjankowski @zhaobzh 
Thanks to @mrsauravsahu's PR we now have the functionality to set the strictSSL under the options tab 🚀

**Comment by peipeiguo** [comment]
Great job! Thanks, now I can set `Options Strict SSL:No` to ignore ssl check.
