### ISSUE TITLE
UI is small

### ISSUE THREAD

**Issue by xypnox** [rohinivsenthil/postcode#32]
The UI is pretty small. The fonts being thin are not visible properly on a large window.

Either changing the fonts to a bolder variant, or increasing the size of the app based on editor font size could be two solutions.

The other actionable buttons are fine but the input font is illegible.

Here is a screenshot for reference:

![Screenshot 2021-08-16 at 2 35 40 PM](https://user-images.githubusercontent.com/25076171/129539136-a8c14a67-1be9-4051-874c-d55fe12c934c.png)

**Comment by rohinivsenthil** [comment]
@xypnox Thanks for bringing this up - I think having the font based on the editor font size would be ideal. Will make this change in the next release 😄

**Comment by rohinivsenthil** [comment]
Made font size relative to editor size with latest release (1.3.9)
